# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinchApp

  target 'FinchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinchAppUITests' do
    # Pods for testing
  end

end
